apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io/'
    targetRevision: v1.6.1
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
