apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubed
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kubed
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.appscode.com/stable/'
    targetRevision: v0.12.0
    chart: kubed
    helm:
      values: |
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "1024Mi"
          enableAnalytics: false
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
