apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kvb-rad-backend
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: springboot-helm-chart
    helm:
      values: |
        nameOverride: kvb-rad-backend
        image: 
          repository: crowdsalat/kvb-rad
          tag: "v.0.6.1-pre"
        secretRef:
          - cockroach-user-kvb-rad-user
        properties:
          api.graphhopper.route.url: http://graphhopper-server:8989/route
          spring.jpa.database: POSTGRESQL
          spring.datasource.username: kvb-rad
          spring.datasource.url: jdbc:postgresql://free-tier13.aws-eu-central-1.cockroachlabs.cloud:26257/kvbbike-db?options=--cluster%3Dcrowdsalat-1065&sslmode=verify-full
        ingress:
          enabled: true
          hosts:
            - host: kvb.weyrich.dev
              paths:
                - path: /tours
                  pathType: Prefix
                - path: /bikes
                  pathType: Prefix
          # configure certmanager: https://cert-manager.io/docs/usage/ingress/#how-it-works
          tls:
            - hosts:
              - argocd.weyrich.dev
              secretName: kvb-rad-backend
          annotations:
            cert-manager.io/cluster-issuer: cloudflare-dns-acme-ca
            kubernetes.io/ingress.class: traefik
    repoURL: https://viadee.github.io/springboot-helm-chart
    targetRevision: 1.1.0
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
