apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kvb-rad-frontend
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: node
    helm:
      parameters:
      - name: image.repository
        value: "crowdsalat/kvb-rad-ui"
      - name: image.tag
        value: "0.13"
      - name: nameOverride
        value: "kvb-rad-frontend"
      - name: containerPorts.http
        value: "8080"
      - name: mongodb.enabled
        value: "false"
      - name: command
        value: "http-server dist"  
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 19.1.7
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
