apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kvb-rad-frontend
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: application
    helm:
      values: |
        applicationName: kvb-rad-frontend
        deployment:
          image: 
            repository: crowdsalat/kvb-rad-ui
            tag: "0.13"
          containerSecurityContext:
            runAsNonRoot: false
        service.ports: 8080
        ingress:
          enabled: true
          ingressClassName: traeffik
          hosts: 
            - host: kvb.weyrich.dev
          servicePort: 8080
          tls:
            - hosts:
              - argocd.weyrich.dev
              secretName: kvb-rad-backend-secret
          annotations:
            cert-manager.io/cluster-issuer: cloudflare-dns-acme-ca
            kubernetes.io/ingress.class: traefik
        rbac:
          enabled: true
          serviceAccount:
            enabled: true
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 2.1.13
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
