apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-config
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: deployment/03_apps/config-argocd
    repoURL: 'https://github.com/CrowdSalat/k3s-cluster'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
