apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kvb-rad-backend
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: spring-boot-helm-chart
    helm:
      parameters:
      - name: image.repository
        value: crowdsalat/kvb-rad
      - name: image.tag
        value: v.0.5.0-pre
      - name: nameOverride
        value: kvb-rad-backend
      - name: config.secretRef[0]
        value: cockroach-user-kvb-rad-user
      - name: config.plain
        value: |-
          api.graphhopper.route.url: graphhopper-server:8989/route
          spring.datasource.username: kvb-rad
    repoURL: https://viadee.github.io/spring-boot-helm-chart
    targetRevision: 0.5.0
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
