apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealedsecrets
spec:
  destination:
    name: ''
    # use this namespace so you do not need to set --controller-namespace= everytime you call kubeseal
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: 2.0.0
    chart: sealed-secrets
    # use this name so you do not need to set --controller-name= everytime you call kubeseal
    helm:
      parameters:
        - name: fullnameOverride
          value: 'sealed-secrets-controller'
        - name: 'crd.create'
          value: 'true'
        - name: 'crd.keep'
          value: 'true'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true