apiVersion: v1
kind: Service
metadata:
  namespace: apps
  labels:
    app: graphhopper-server
  name: graphhopper-server
spec:
  ports:
  - port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    app: graphhopper-server
