apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
  annotation:
    cert-manager.io/cluster-issuer: cloudflare-dns-acme-ca
spec:
  rules:
    - host: whoami.weyrich.dev
      http:
        paths:
          - backend:
              service:
                name: whoami-service
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - whoami.weyrich.dev
      secretName: whoami-ingress-secret